#!/bin/bash

source .env
[ -f .env.local ] && source .env.local

echo Deploying to $DEPLOY_TARGET

tar cf - --no-xattrs index.js package.* node_modules > app.tar
ls -l app.tar
cat app.tar | ssh $DEPLOY_TARGET 'cd logger && rm -rf * && tar xf -'
rm app.tar
